### ISSUE TITLE
[Feature Suggestion] HTML option for Marky Dynamic

### ISSUE THREAD

**Issue by etherealxx** [robole/vscode-marky-markdown#3]
### Hello👋 Really loves your extension, absolutely helpful!
However, i'm curious, is this repo still maintained, and if yes, can you add an option to turn the generated 'table of content' into a html one? So it can become a dropwdown list like this:

<details>
  <summary>Table of Contents</summary>
  <ol>
    <li><a href="#installation">Installation</a></li>
    <li><a href="#about">About</a></li>
    <li><a href="#example">Example</a></li>
    <li><a href="#syntax">Syntax</a></li>
      <ul><li><a href="#valid-hashtags">Valid Hashtags</a></li></ul>
    </li>
  </ol>
</details>

i use this code to manually turn the generated TOC from your extension into the html one. (it's not perfect, it also has flaws, since I'm a noob, but i hope you got my point)
```
intro = """
<details>
  <summary>Table of Contents</summary>
  <ol>
"""

outro = """
    </li>
  </ol>
</details>
"""

tableofcontents = """
- [Installation](#installation)
- [About](#about)
- [Example](#example)
- [Syntax](#syntax)
  - [Valid Hashtags](#valid-hashtags)
"""

def mlineprint(toprint):
    if toprint[-1] == '\n':
        toprint = toprint[:-1]
    print(toprint.replace('\n', '', 1))


def writehtmllist(space, namehead, hashtaghead):
    spaces = ""
    for _ in range(space):
        spaces += " "
    if initialspace >= 2:
        return spaces + f'<ul><li><a href="{hashtaghead}">{namehead}</a></li></ul>'
    else:
        return spaces + f'<li><a href="{hashtaghead}">{namehead}</a></li>'

if __name__ == "__main__":
    rows = tableofcontents.replace('\n', '', 1).splitlines()#split('\n')  # split into a list of rows
    mlineprint(intro)
    for row in rows:
        if not row == '':
            initialspace = 0
            for char in row:
                if char == ' ':
                    initialspace += 1
                else:
                    break
            extractedrow = row.split("[")
            cuttedrow = extractedrow[1].partition("](")
            headingname = cuttedrow[0]
            headinghashtag = cuttedrow[2].rstrip(")")
            print(writehtmllist(initialspace+4, headingname, headinghashtag))
    mlineprint(outro)
```

That's from me. I don't know if it's possible (i mean easy to implement) or not, and if you don't want to implement it, that's totally okay!

I hope you an amazing day✨

**Comment by robole** [comment]
Hi @etherealxx ,

What is the outcome you want?

Is it just to have a table of contents inside a collapsible section in a REAME.md?

For example, GitHub allows you to [create a collapsible section](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/organizing-information-with-collapsed-sections#creating-a-collapsed-section) in a markdown file by wrapping markdown inside of `details` and `summary`  HTML elements like this:

```
<details>

<summary>Tips for collapsed sections</summary>

### You can add a header

You can add text within a collapsed section. 

You can add an image or a code block, too.

</details>

```

If that is want you want, you can just wrap the table of contents in a `details` element and it will show up on GitHub..

**Comment by etherealxx** [comment]
Damn, i really didn't know about that, sorry😅

But i tried with the one generated with your extension
![image](https://user-images.githubusercontent.com/64251396/226190143-0f3a5b69-c9f6-489c-b5a4-cdf687ef8654.png)

This is the result 🤔
![image](https://user-images.githubusercontent.com/64251396/226190176-5ad1a3b4-be7e-4c6d-8367-cef67cf815ba.png)

Not what i'm expecting😅

This is the outcome i wanted:
![image](https://user-images.githubusercontent.com/64251396/226190248-f1bc54c9-b062-4186-ae85-292e480ea359.png)

**Comment by robole** [comment]
Yes, that output is as expected. Did you commit the changes to the markdown file and view it on GitHub?

What matters is the conversion of markdown -> HTML on the platform you are using.  It is the markdown parser that determines how it deals with that output.
